[2025-05-18T01:51:09.281+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:51:02.551148+00:00/task_id=merge_data permission to 509
[2025-05-18T01:51:09.281+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:51:02.551148+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:51:02.551148+00:00/task_id=merge_data'
[2025-05-18T01:51:09.304+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:51:02.551148+00:00/task_id=merge_data permission to 509
[2025-05-18T01:51:09.305+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:51:02.551148+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:51:02.551148+00:00/task_id=merge_data'
[2025-05-18T01:51:09.337+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-18T01:51:02.551148+00:00 [queued]>
[2025-05-18T01:51:09.343+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-18T01:51:02.551148+00:00 [queued]>
[2025-05-18T01:51:09.344+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-05-18T01:51:09.354+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): merge_data> on 2025-05-18 01:51:02.551148+00:00
[2025-05-18T01:51:09.360+0000] {standard_task_runner.py:60} INFO - Started process 222 to run task
[2025-05-18T01:51:09.362+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'merge_data', 'manual__2025-05-18T01:51:02.551148+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmp4i7e_upa']
[2025-05-18T01:51:09.364+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask merge_data
[2025-05-18T01:51:09.402+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:51:02.551148+00:00/task_id=merge_data permission to 509
[2025-05-18T01:51:09.403+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:51:02.551148+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-18T01:51:02.551148+00:00/task_id=merge_data'
[2025-05-18T01:51:09.404+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dimensional_model.merge_data manual__2025-05-18T01:51:02.551148+00:00 [running]> on host f5c47913001e
[2025-05-18T01:51:09.577+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T01:51:02.551148+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-18T01:51:02.551148+00:00'
[2025-05-18T01:51:20.923+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-18T01:51:20.933+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=merge_data, execution_date=20250518T015102, start_date=20250518T015109, end_date=20250518T015120
[2025-05-18T01:51:20.961+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-18T01:51:20.978+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
