[2025-05-21T21:09:34.489+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T21:09:21.381131+00:00/task_id=merge_data permission to 509
[2025-05-21T21:09:34.490+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T21:09:21.381131+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T21:09:21.381131+00:00/task_id=merge_data'
[2025-05-21T21:09:34.512+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T21:09:21.381131+00:00/task_id=merge_data permission to 509
[2025-05-21T21:09:34.512+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T21:09:21.381131+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T21:09:21.381131+00:00/task_id=merge_data'
[2025-05-21T21:09:34.540+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-21T21:09:21.381131+00:00 [queued]>
[2025-05-21T21:09:34.546+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-21T21:09:21.381131+00:00 [queued]>
[2025-05-21T21:09:34.546+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-05-21T21:09:34.558+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): merge_data> on 2025-05-21 21:09:21.381131+00:00
[2025-05-21T21:09:34.564+0000] {standard_task_runner.py:60} INFO - Started process 345 to run task
[2025-05-21T21:09:34.566+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'merge_data', 'manual__2025-05-21T21:09:21.381131+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmpj4d96q83']
[2025-05-21T21:09:34.569+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask merge_data
[2025-05-21T21:09:34.608+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T21:09:21.381131+00:00/task_id=merge_data permission to 509
[2025-05-21T21:09:34.608+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T21:09:21.381131+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T21:09:21.381131+00:00/task_id=merge_data'
[2025-05-21T21:09:34.609+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dimensional_model.merge_data manual__2025-05-21T21:09:21.381131+00:00 [running]> on host 17029009782b
[2025-05-21T21:09:34.670+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T21:09:21.381131+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T21:09:21.381131+00:00'
[2025-05-21T21:09:36.194+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-21T21:09:36.202+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=merge_data, execution_date=20250521T210921, start_date=20250521T210934, end_date=20250521T210936
[2025-05-21T21:09:36.223+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-21T21:09:36.243+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
